ALTER TYPE "public"."RequestStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN' AFTER 'DRAFT';
ALTER TYPE "public"."AuditAction" ADD VALUE IF NOT EXISTS 'REQUEST_UPDATED' AFTER 'REQUEST_CREATED';
ALTER TYPE "public"."AuditAction" ADD VALUE IF NOT EXISTS 'REQUEST_WITHDRAWN' AFTER 'REQUEST_SUBMITTED';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'REQUEST_WITHDRAWN' AFTER 'APPROVAL_ASSIGNED';
